declare module '@walletconnect/web3-provider'
declare type Maybe<T> = T | null
declare module 'apollo-link-logger'
declare module '@gnosis.pm/conditional-tokens-contracts/utils/id-helpers'
declare module 'react-copy-to-clipboard'
declare module '@realitio/realitio-lib/formatters/question'
declare module '@realitio/realitio-lib/formatters/template'
declare type KnownOracle = 'kleros' | 'realitio' | 'unknown'
declare type KnownArbitrator = 'kleros' | 'realitio' | 'unknown'
declare module '*.woff2'
declare module './theme'
